name: build
on:
  push:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: megalinter
        uses: oxsecurity/megalinter/flavors/python@beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
